FROM node:18 as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /usr/src/app/dist/datahub_app_v2/browser /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY infra/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
